### ISSUE TITLE
Suggestion: Make username in users on SQL to be Unique

### ISSUE THREAD

**Issue by YuKARLO15** [YuKARLO15/SalesInventorySystem_WAM1#11]
Would there be any problems if we make the username of the users in our SQL database to be unique. I noticed kasi na it would make a duplicate entry if same username nilagay which baka malito system sa pag login. 

Also Date Added on Inventory doesn't show the time, it only shows 00:00:00 but it shows on the database naman. Also last login sa users.

I did try it na sa local copy ko na naka Unique but I haven't pushed it sa Server na folder, saka does it need try catch pa? Well it shows naman yung error sa Release build and it doesn't crash naman, sa Debug lang naman siya nag crash or break pag ganon eh.

Saka try ko nadin yung change password if ever.

(Overall checked the system and everything works properly, except for yung sinabi ko sa duplicate sa add users. Also haven't tried pa if malaki/marami na yung datas na nakalagay)

**Comment by YuKARLO15** [comment]
Ohh, wait ayusin ko pala itsura nung data grid view, di naka fit eh

**Comment by YuKARLO15** [comment]
> Ohh, wait ayusin ko pala itsura nung data grid view, di naka fit eh

Done na on this pushed na, I made the forms wider and set yung AutoSizeColumnsMode into Fill.

**Comment by Chris1320** [comment]
> Would there be any problems if we make the username of the users in our SQL database to be unique. I noticed kasi na it would make a duplicate entry if same username nilagay which baka malito system sa pag login.

Tracking in PR #14

**Comment by Chris1320** [comment]
> Also Date Added on Inventory doesn't show the time, it only shows 00:00:00 but it shows on the database naman. Also last login sa users.

Tracking in PR #15
